name: Test HelloCall Models
on: [push]
jobs:
  run-demo:
    runs-on: ubuntu-latest
    env:
      HELLOCALL_MODELS_TOKEN: ${{ secrets.HELLOCALL_MODELS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Python script
        run: python scripts/run_github_models_demo.py
